version: '3.1'

services:
    web:
        build: .
        restart: always
        ports:
            - '3000:3000'
    db:
        image: postgres:14.2-alpine
        restart: always
        environment:
            POSTGRES_DB: groceryDB
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password123
        ports:
            - '5432:5432'
        volumes:
            - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
